version: '3'

services:
  darkbot:
    build: .
    container_name: darkbot
    platform: linux/amd64
    ports:
      - "5900:5900"  # VNC port
    volumes:
      - ./darkbot:/home/darkbot/darkbot
      - ./config:/mnt/darkbot/config
    environment:
      - DISPLAY=:1
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    restart: unless-stopped
    networks:
      - darkbot_network

networks:
  darkbot_network:
    driver: bridge